#PROD environment

app:
  message: 'This is the property file fo the ${spring.application.name} specific to DEV Environment'

amazon:
  dynamodb:
    endpoint: 'http://localhost:8000'
  aws:
    accesskey: 'The AWSCLI access key overrides this one.'
    secretkey: 'The AWSCLI secret key overrides this one.'
