#DEV environment

spring:
  config:
    activate:
      on-profile: dev

amazon:
  dynamodb:
    endpoint: http://172.18.0.1:8000
  aws:
    signInRegion: east-us-1
    accessKeyId: The AWSCLI access key overrides this one.
    secretKey: The AWSCLI access key overrides this one.
