#DEV environment

app:
  message: 'This is the property file fo the ${spring.application.name} specific to DEV Environment'

amazon:
  dynamodb:
    endpoint: 'http://localhost:8000'
  aws:
    access_key: 'The AWSCLI access key overrides this one.'
    secret_key: 'The AWSCLI secret key overrides this one.'
    sign_in_region: 'east-us-1'
